# Generated by Django 4.2 on 2023-09-21 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmembers",
            unique_together={("project", "user")},
        ),
    ]
