# Generated by Django 4.2.5 on 2023-10-10 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectmembership_delete_projectmembers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmembership",
            old_name="is_admin",
            new_name="is_project_admin",
        ),
    ]
