# Generated by Django 4.2.10 on 2024-02-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0005_remove_metadatatemplate_project_and_more"),
        ("projects", "0004_rename_is_admin_projectmembership_is_project_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetadata",
            fields=[
                (
                    "metadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.metadata",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.metadata",),
        ),
    ]
