# Generated by Django 4.2.10 on 2024-02-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_projectmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
