# Generated by Django 4.2.10 on 2024-03-14 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_project_description"),
        ("metadata", "0007_migrate_metadata_proxy_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectMetadata",
        ),
    ]
