# Generated by Django 4.2.10 on 2024-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_delete_projectmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members_count",
            field=models.IntegerField(default=0),
        ),
    ]
