# Generated by Django 4.2.16 on 2024-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_locked_project_locked_at_project_locked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_deletable",
            field=models.BooleanField(default=True),
        ),
    ]
