# Generated by Django 4.2.16 on 2024-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_retroactively_migrate_is_deleteable"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="is_metadata_template_admin",
            field=models.BooleanField(default=False),
        ),
    ]
