# Generated by Django 4.2.20 on 2025-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_project_metadata_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="metadata_templates_count",
            field=models.IntegerField(default=0),
        ),
    ]
