# Generated by Django 4.2.16 on 2024-11-05 10:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_fernet.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storages", "0003_create_default_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicStorage",
            fields=[
                ("creation_date", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("last_modification_date", models.DateTimeField(auto_now=True, verbose_name="Last modification date")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.JSONField(blank=True, default=dict)),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("default_local", "Default Local Storage")],
                        default="default_local",
                        help_text="Type of storage provider",
                        max_length=32,
                    ),
                ),
                (
                    "text_encrypted_example",
                    django_fernet.fields.FernetTextField(
                        blank=True,
                        null=True,
                        verbose_name="An example encrypted text field that could be used for credentials",
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who created this element",
                    ),
                ),
                (
                    "last_modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who last modified this element",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage",
                "verbose_name_plural": "Storages",
                "indexes": [
                    models.Index(fields=["storage_type"], name="storages_dy_storage_a45af3_idx"),
                    models.Index(fields=["default"], name="storages_dy_default_ad967f_idx"),
                ],
            },
        ),
    ]
