# Generated by Django 4.2.16 on 2024-11-18 07:50

from django.db import migrations

import django_fernet.fields


class Migration(migrations.Migration):
    dependencies = [
        ("storages", "0005_create_default_dynamic_storage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicstorage",
            name="text_encrypted_example",
        ),
        migrations.AddField(
            model_name="dynamicstorage",
            name="local_private_dss_path_encrypted",
            field=django_fernet.fields.FernetTextField(
                blank=True,
                null=True,
                verbose_name="The path of a locally mounted private DSS container.",
            ),
        ),
    ]
