# Generated by Django 4.2.16 on 2024-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storages", "0006_remove_dynamicstorage_text_encrypted_example_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicstorage",
            name="storage_type",
            field=models.CharField(
                choices=[("default_local", "Default Local Storage"), ("private_dss", "Private DSS Storage")],
                default="default_local",
                help_text="Type of storage provider",
                max_length=32,
            ),
        ),
    ]
