# Generated by Django 4.2.18 on 2025-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storages", "0007_alter_dynamicstorage_storage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicstorage",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dynamicstorage",
            name="mounted",
            field=models.BooleanField(default=False),
        ),
    ]
