# Generated by Django 1.11.8 on 2017-12-14 15:01
from django.db import migrations

import fdm.users.models.managers


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0008_alter_user_username_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", fdm.users.models.managers.GroupManager()),
            ],
        ),
    ]
