# Generated by Django 4.2.11 on 2024-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anonymized",
            field=models.BooleanField(default=False),
        ),
    ]
