# Generated by Django 4.2.14 on 2024-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_migrate_member_group_to_user_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_create_projects",
            field=models.BooleanField(default=False),
        ),
    ]
