# Generated by Django 4.2.15 on 2024-09-05 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="im_org_zug_gast_lang",
            new_name="im_org_zug_gast",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="im_org_zug_mitarbeiter_lang",
            new_name="im_org_zug_mitarbeiter",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="im_org_zug_student_lang",
            new_name="im_org_zug_student",
        ),
    ]
