# Generated by Django 4.2.16 on 2024-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_rename_im_org_zug_gast_lang_user_im_org_zug_gast_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authentication_provider",
            field=models.CharField(
                choices=[("APPLICATION", "Application"), ("SHIBBOLETH", "Shibboleth")],
                default="APPLICATION",
                max_length=16,
            ),
        ),
    ]
