# Generated by Django 4.2.16 on 2025-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_authentication_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_global_metadata_template_admin",
            field=models.BooleanField(default=False),
        ),
    ]
