# Generated by Django 4.2.19 on 2025-03-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_is_global_metadata_template_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_global_approval_queue_admin",
            field=models.BooleanField(default=False),
        ),
    ]
