# Generated by Django 4.2.14 on 2024-07-31 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shibboleth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shibbolethauthcode",
            name="used",
        ),
    ]
