# Generated by Django 4.2 on 2023-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsversionfile",
            name="file_upload",
            field=models.FileField(upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
