# Generated by Django 4.2 on 2023-04-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_alter_uploadsversion_dataset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsversionfile",
            name="uploads_version",
        ),
        migrations.AddField(
            model_name="uploadsversion",
            name="version_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads_versions",
                to="uploads.uploadsversionfile",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsversion",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads_version",
                to="uploads.uploadsdataset",
            ),
        ),
    ]
