# Generated by Django 4.2 on 2023-04-19 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import django_userforeignkey.models.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploads", "0006_uploadsdataset_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsdataset",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who created this element",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsdataset",
            name="last_modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who last modified this element",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsversion",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who created this element",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsversion",
            name="last_modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who last modified this element",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsversionfile",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who created this element",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsversionfile",
            name="last_modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who last modified this element",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsversionmetadata",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who created this element",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsversionmetadata",
            name="last_modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who last modified this element",
            ),
        ),
    ]
