# Generated by Django 4.2 on 2023-04-19 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploads", "0007_alter_uploadsdataset_created_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel("uploadsversionmetadata"),
    ]
