# Generated by Django 4.2 on 2023-04-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0001_initial"),
        ("uploads", "0008_drop_table_uploadsversionmetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadsVersionMetadata",
            fields=[
                (
                    "metadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.metadata",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="uploads.uploadsversion",
                        verbose_name="Uploads version",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.metadata",),
        ),
        migrations.CreateModel(
            name="UploadsVersionFileMetadata",
            fields=[
                (
                    "metadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.metadata",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="uploads.uploadsversionfile",
                        verbose_name="Version file",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.metadata",),
        ),
    ]
