# Generated by Django 4.2 on 2023-04-19 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0009_uploadsversionmetadata_uploadsversionfilemetadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsversionfile",
            name="checksum_sha256",
        ),
    ]
