# Generated by Django 4.2 on 2023-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0010_remove_uploadsversionfile_checksum_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsversionfile",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
