# Generated by Django 4.2.1 on 2023-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0011_uploadsversionfile_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsversionfile",
            name="processed",
        ),
        migrations.AddField(
            model_name="uploadsversionfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("PROCESSED", "Processed"),
                    ("IN_PROGRESS", "In progress"),
                    ("ERROR", "Error"),
                    ("FINISHED", "Finished"),
                ],
                default="SCHEDULED",
                max_length=16,
            ),
        ),
    ]
