# Generated by Django 4.2.5 on 2023-09-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0012_remove_uploadsversionfile_processed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadsversionfile",
            old_name="file_upload",
            new_name="uploaded_file",
        ),
        migrations.AddField(
            model_name="uploadsversionfile",
            name="uploaded_using_tus",
            field=models.BooleanField(default=False),
        ),
    ]
