# Generated by Django 4.2 on 2023-10-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0002_foldermembers_permission"),
        ("uploads", "0013_rename_file_upload_uploadsversionfile_uploaded_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsdataset",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads_dataset",
                to="folders.folder",
            ),
        ),
        migrations.AddField(
            model_name="uploadsversion",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publication date"),
        ),
    ]
