# Generated by Django 4.2 on 2023-10-05 07:06

from django.db import migrations

import fdm.storages.models.models
import fdm.uploads.models.models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0014_uploadsdataset_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsversionfile",
            name="uploaded_file",
            field=fdm.storages.models.models.DynamicStorageFileField(
                max_length=4096,
                upload_to=fdm.uploads.models.models.get_upload_to_path,
            ),
        ),
    ]
