# Generated by Django 4.2 on 2023-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0015_alter_uploadsversionfile_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsversionfile",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publication date"),
        ),
    ]
