# Generated by Django 4.2.10 on 2024-03-14 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0016_uploadsversionfile_publication_date"),
        ("metadata", "0007_migrate_metadata_proxy_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsversionmetadata",
            name="metadata_ptr",
        ),
        migrations.RemoveField(
            model_name="uploadsversionmetadata",
            name="relation",
        ),
        migrations.DeleteModel(
            name="UploadsVersionFileMetadata",
        ),
        migrations.DeleteModel(
            name="UploadsVersionMetadata",
        ),
    ]
