# Generated by Django 4.2.10 on 2024-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0017_remove_uploadsversionmetadata_metadata_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsversion",
            name="metadata_is_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uploadsversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("IN_PROGRESS", "In progress"),
                    ("ERROR", "Error"),
                    ("FINISHED", "Finished"),
                ],
                default="SCHEDULED",
                max_length=16,
            ),
        ),
    ]
