# Generated by Django 4.2.13 on 2024-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0018_uploadsversion_metadata_is_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsversion",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
