# Generated by Django 4.2.13 on 2024-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0020_uploadsdataset_locked_uploadsdataset_locked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsdataset",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publication date"),
        ),
    ]
