# Generated by Django 4.2.15 on 2024-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0022_migrate_uploads_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsdataset",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
