# Generated by Django 4.2.15 on 2024-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0024_migrate_uploadsdataset_sort_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsdataset",
            name="description",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
