# Generated by Django 4.2.15 on 2024-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0025_uploadsdataset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsversionfile",
            name="storage_relocating",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("PROCESSED", "Processed"),
                    ("IN_PROGRESS", "In progress"),
                    ("ERROR", "Error"),
                    ("FINISHED", "Finished"),
                ],
                default="FINISHED",
                max_length=16,
            ),
        ),
    ]
