# Generated by Django 4.2.16 on 2024-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0026_uploadsversionfile_storage_relocating"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsdataset",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expiry date"),
        ),
    ]
