# Generated by Django 4.2.16 on 2024-11-07 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0028_migrate_uploadsdataset_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsdataset",
            name="description",
        ),
    ]
