# Generated by Django 4.2.16 on 2024-11-05 10:15

from django.db import migrations

import fdm.storages.fields.dynamic_storage
import fdm.uploads.models.models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0029_remove_uploadsdataset_description"),
        ("storages", "0005_create_default_dynamic_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsversionfile",
            name="uploaded_file",
            field=fdm.storages.fields.dynamic_storage.DynamicRuntimeStorageFileField(
                max_length=4096,
                upload_to=fdm.uploads.models.models.get_upload_to_path,
            ),
        ),
    ]
