# Generated by Django 4.2.20 on 2025-03-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0030_alter_uploadsversionfile_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsversionfile",
            name="is_referenced",
            field=models.BooleanField(default=False),
        ),
    ]
