# Generated by Django 4.2.20 on 2025-03-25 06:28

from django.db import migrations

import fdm.storages.fields.dynamic_storage
import fdm.uploads.models.models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0031_uploadsversionfile_is_referenced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsversionfile",
            name="uploaded_file",
            field=fdm.storages.fields.dynamic_storage.DynamicRuntimeStorageFileField(
                blank=True,
                max_length=4096,
                null=True,
                upload_to=fdm.uploads.models.models.get_upload_to_path,
            ),
        ),
    ]
