# Generated by Django 4.2 on 2023-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldermembers",
            name="permission",
            field=models.CharField(choices=[("EDIT", "Edit"), ("VIEW", "View")], default="VIEW", max_length=4),
        ),
    ]
