# Generated by Django 4.2.5 on 2023-10-10 11:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectmembership_delete_projectmembers"),
        ("folders", "0002_foldermembers_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolderPermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("folder", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="folders.folder")),
                (
                    "project_membership",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.projectmembership"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="FolderMembers",
        ),
    ]
