# Generated by Django 4.2.5 on 2023-10-10 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0003_folderpermission_delete_foldermembers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="folderpermission",
            old_name="is_admin",
            new_name="is_folder_admin",
        ),
    ]
