# Generated by Django 4.2 on 2023-10-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storages", "0001_initial"),
        ("folders", "0004_rename_is_admin_folderpermission_is_folder_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="storage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder",
                to="storages.storage",
            ),
        ),
    ]
