# Generated by Django 4.2.6 on 2023-11-13 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_rename_is_admin_projectmembership_is_project_admin"),
        ("folders", "0005_folder_storage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="folderpermission",
            unique_together={("folder", "project_membership")},
        ),
    ]
