# Generated by Django 4.2.8 on 2023-12-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0002_metadatatemplate_metadatatemplatefield"),
        ("folders", "0006_alter_folderpermission_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="metadata_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder",
                to="metadata.metadatatemplate",
            ),
        ),
    ]
