# Generated by Django 4.2.10 on 2024-02-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0004_alter_metadatatemplatefield_field_and_more"),
        ("folders", "0007_folder_metadata_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolderMetadata",
            fields=[
                (
                    "metadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.metadata",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="folders.folder",
                        verbose_name="Folder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.metadata",),
        ),
    ]
