# Generated by Django 4.2.11 on 2024-04-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0013_folder_locked_folder_locked_at_folder_locked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="description",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
