# Generated by Django 4.2.13 on 2024-07-26 12:45

import django.db.models.deletion
from django.db import migrations, models

import fdm.folders.models.models


class Migration(migrations.Migration):
    dependencies = [
        ("storages", "0003_create_default_storage"),
        ("folders", "0017_migrate_default_folder_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="storage",
            field=models.ForeignKey(
                blank=True,
                default=fdm.folders.models.models.get_default_folder_storage,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="folder",
                to="storages.storage",
            ),
        ),
    ]
