# Generated by Django 4.2.16 on 2024-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0019_recalculate_folder_datasets_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="folderpermission",
            name="is_metadata_template_admin",
            field=models.BooleanField(default=False),
        ),
    ]
