# Generated by Django 4.2.16 on 2025-01-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0009_metadatatemplatefield_field_type"),
        ("folders", "0020_folderpermission_is_metadata_template_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="metadata_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folder",
                to="metadata.metadatatemplate",
            ),
        ),
    ]
