# Generated by Django 4.2.20 on 2025-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0022_alter_folder_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="metadata_templates_count",
            field=models.IntegerField(default=0),
        ),
    ]
