# Generated by Django 4.2.8 on 2023-12-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_rename_is_admin_projectmembership_is_project_admin"),
        ("metadata", "0002_metadatatemplate_metadatatemplatefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadatatemplate",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_template",
                to="projects.project",
            ),
        ),
    ]
