# Generated by Django 4.2.9 on 2024-01-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0003_metadatatemplate_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatatemplatefield",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_template_fields",
                to="metadata.metadatafield",
            ),
        ),
        migrations.AlterField(
            model_name="metadatatemplatefield",
            name="metadata_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_template_fields",
                to="metadata.metadatatemplate",
            ),
        ),
    ]
