# Generated by Django 4.2.10 on 2024-02-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("metadata", "0004_alter_metadatatemplatefield_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metadatatemplate",
            name="project",
        ),
        migrations.AddField(
            model_name="metadatatemplate",
            name="assigned_to_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="metadatatemplate",
            name="assigned_to_object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="metadatatemplate",
            index=models.Index(
                fields=["assigned_to_content_type", "assigned_to_object_id"],
                name="metadata_me_assigne_521c90_idx",
            ),
        ),
    ]
