# Generated by Django 4.2.16 on 2024-09-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0007_migrate_metadata_proxy_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="field_type",
            field=models.CharField(
                choices=[("INTEGER", "Integer"), ("DECIMAL", "Decimal"), ("TEXT", "Text")],
                default="TEXT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="metadatafield",
            name="field_type",
            field=models.CharField(
                choices=[("INTEGER", "Integer"), ("DECIMAL", "Decimal"), ("TEXT", "Text")],
                default="TEXT",
                max_length=16,
            ),
        ),
    ]
