# Generated by Django 4.2.16 on 2024-10-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0008_metadata_field_type_alter_metadatafield_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadatatemplatefield",
            name="field_type",
            field=models.CharField(
                choices=[("INTEGER", "Integer"), ("DECIMAL", "Decimal"), ("TEXT", "Text")],
                default="TEXT",
                max_length=16,
            ),
        ),
    ]
