# Generated by Django 4.2.16 on 2024-11-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0009_metadatatemplatefield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="metadatafield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="metadatatemplatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
    ]
