# Generated by Django 4.2.16 on 2024-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0011_migrate_metadata_field_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="value_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="metadatatemplatefield",
            name="value_json",
            field=models.JSONField(blank=True, null=True, default=None),
        ),
    ]
