# Generated by Django 4.2.16 on 2024-11-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0014_migrate_metadata_template_field_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
