# Generated by Django 4.2.16 on 2024-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0017_migrate_metadata_template_field_values"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metadata",
            old_name="value",
            new_name="value_old",
        ),
        migrations.RenameField(
            model_name="metadata",
            old_name="value_json",
            new_name="value",
        ),
        migrations.RenameField(
            model_name="metadatatemplatefield",
            old_name="value",
            new_name="value_old",
        ),
        migrations.RenameField(
            model_name="metadatatemplatefield",
            old_name="value_json",
            new_name="value",
        ),
    ]
