# Generated by Django 4.2.16 on 2024-11-11 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0018_rename_value_json_metadata_value_old_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metadata",
            name="value_old",
        ),
        migrations.RemoveField(
            model_name="metadatatemplatefield",
            name="value_old",
        ),
    ]
