# Generated by Django 4.2.17 on 2025-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0019_remove_metadata_value_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("DATE", "Date"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="metadatafield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("DATE", "Date"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="metadatatemplatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("DATE", "Date"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
    ]
