# Generated by Django 4.2.19 on 2025-02-24 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_userforeignkey.models.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metadata", "0022_alter_metadata_field_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadatatemplate",
            name="locked",
            field=models.BooleanField(default=False, verbose_name="Whether this element is locked"),
        ),
        migrations.AddField(
            model_name="metadatatemplate",
            name="locked_at",
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Locked at"),
        ),
        migrations.AddField(
            model_name="metadatatemplate",
            name="locked_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_locked_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who locked this element",
            ),
        ),
    ]
