# Generated by Django 4.2.19 on 2025-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0023_metadatatemplate_locked_metadatatemplate_locked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("DATETIME", "Date & Time"),
                    ("DATE", "Date"),
                    ("TIME", "Time"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                    ("SELECTION", "Selection"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="metadatafield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("DATETIME", "Date & Time"),
                    ("DATE", "Date"),
                    ("TIME", "Time"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                    ("SELECTION", "Selection"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="metadatatemplatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("DATETIME", "Date & Time"),
                    ("DATE", "Date"),
                    ("TIME", "Time"),
                    ("TEXT", "Text"),
                    ("WYSIWYG", "WYSIWYG editor"),
                    ("SELECTION", "Selection"),
                ],
                default="TEXT",
                max_length=16,
            ),
        ),
    ]
