# Generated by Django 4.2.19 on 2025-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0024_alter_metadata_field_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="metadatatemplatefield",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
