# Generated by Django 4.2.20 on 2025-03-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0026_migrate_metadata_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="metadata_template_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metadata",
                to="metadata.metadatatemplatefield",
            ),
        ),
    ]
