# Generated by Django 4.2.20 on 2025-03-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0027_metadata_metadata_template_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="value",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="metadatatemplatefield",
            name="value",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
