# Generated by Django 4.2 on 2023-08-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbsettings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
