# Generated by Django 4.2 on 2023-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbsettings", "0002_setting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="key",
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
