# Generated by Django 4.2 on 2023-08-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbsettings", "0004_app_title_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
