# Generated by Django 4.2.17 on 2025-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbsettings", "0009_version_name_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
