# Generated by Django 4.2.7 on 2023-11-13 11:09

from django.db import migrations
from django.db.migrations import RunPython

GROUP_NAME = "TUM Members"


def add_group_tum_members(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    group, created = Group.objects.get_or_create(name=GROUP_NAME)


def remove_group_tum_members(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=GROUP_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0006_alter_folderpermission_unique_together"),
    ]

    operations = [
        RunPython(
            add_group_tum_members,
            remove_group_tum_members,
        ),
    ]
