# Generated by Django 4.2.5 on 2023-09-11 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_userforeignkey.models.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rest_framework_tus", "0005_alter_upload_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="pk_from_path",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="user",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who uploaded this file",
            ),
        ),
    ]
