# Generated by Django 4.2.5 on 2023-09-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_framework_tus", "0006_upload_pk_from_path_upload_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="uploaded_file",
            field=models.FileField(blank=True, max_length=255, null=True, upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
