# Generated by Django 4.2.15 on 2024-08-27 11:54

from django.db import migrations, models

import fdm.rest_framework_tus.models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_framework_tus", "0008_remove_upload_pk_from_path_upload_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                max_length=4096,
                null=True,
                upload_to=fdm.rest_framework_tus.models.get_upload_to_path,
            ),
        ),
    ]
