# Generated by Django 4.2.16 on 2024-09-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_add_content_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.SlugField(max_length=128, unique=True, verbose_name="URL slug for this content"),
        ),
    ]
