# Generated by Django 4.2.16 on 2024-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_alter_content_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="content",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
