# Generated by Django 4.2 on 2023-05-03 09:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uploads", "0011_uploadsversionfile_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileParser",
            fields=[
                ("creation_date", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("last_modification_date", models.DateTimeField(auto_now=True, verbose_name="Last modification date")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "parser_type",
                    models.CharField(
                        choices=[
                            ("CHECKSUM_MD5", "Checksum MD5"),
                            ("CHECKSUM_SHA256", "Checksum SHA256"),
                            ("CHECKSUM_SHA512", "Checksum SHA512"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In progress"),
                            ("ERROR", "Error"),
                            ("FINISHED", "Finished"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_parser",
                        to="uploads.uploadsversionfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
