# Generated by Django 4.2.1 on 2023-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileparser",
            name="parser_type",
            field=models.CharField(
                choices=[
                    ("CHECKSUM_MD5", "Checksum MD5"),
                    ("CHECKSUM_SHA256", "Checksum SHA256"),
                    ("CHECKSUM_SHA512", "Checksum SHA512"),
                    ("EXIF_DATA", "EXIF data"),
                ],
                max_length=64,
            ),
        ),
    ]
