# Generated by Django 4.2.13 on 2024-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_parser", "0005_migrate_checksums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileparser",
            name="parser_type",
            field=models.CharField(
                choices=[
                    ("CHECKSUM_SHA256", "Checksum SHA256"),
                    ("EXIF_DATA", "EXIF data"),
                    ("MIME_TYPE", "MIME type"),
                    ("FILE_INFORMATION", "File information"),
                ],
                max_length=64,
            ),
        ),
    ]
